#! /bin/sh

set -e
apk add --no-cache openssl
apk add --no-cache --virtual .builddeps \
  build-base \
  cmake \
  openssl-dev \
  ncurses-dev \
  libtirpc-dev \
  rpcgen \
  linux-headers

mkdir -p /usr/src/mysql
tar -xf /src/mysql.tar.gz -C /usr/src/mysql --strip-components=1

mkdir -p /usr/src/build
cd /usr/src/build
cmake \
  -DBUILD_CONFIG=mysql_release \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DCMAKE_BUILD_TYPE=Release \
  -DSYSCONFDIR=/etc/mysql \
  -DMYSQL_DATADIR=/var/lib/mysql \
  -DWITH_DEBUG=false \
  -DWITH_BOOST=/usr/src/mysql/boost \
  ../mysql

make

apk del --no-network .builddeps
